name: Automated e2e testing
on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  run-e2e-tests:
    name: Run e2e Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout under $GITHUB_WORKSPACE
        uses: actions/checkout@main
      - name: Set up NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 21

      - name: Install all dependencies
        run: npm install

      - name: Install Cypress
        run: npm install cypress

      - name: Start server
        run: npm start &
        env:
          CI: true

      - name: Run Tests
        run: npm run test-e2e-cli
